### ISSUE TITLE
Field is not properly reset with default value set to 'false'

### ISSUE THREAD

**Issue by oplaner4** [evilkiwi/form#5]
**Describe the bug**
Boolean field is not properly reset with default value set to 'false'.

**To Reproduce**
1.

```ts
const {
  useField, reset,
} = useForm<{ visible: boolean }>({
  defaults: {
    visible: false,
  },
});

const visible = useField('visible', { type: 'boolean' });
```

2. Call `reset` method.
3. Field `visible` will be reset to `''` (empty string).

**Expected behavior**
With default value set to 'false' boolean field should be reset to `false`.

**Solution**
Check this source line (inaccurate type checking):
```ts
fields.value[key] = options.defaults && options.defaults[key] ? options.defaults[key] : "";
```

Which should be replaced, for instance, with:

```ts
fields.value[key] = typeof options.defaults !== 'undefined' && typeof options.defaults[key] !== 'undefined'
  ? options.defaults[key]
  : '';
```

Note that the same problem occurs with default value set to `null` or `0`.

**Comment by devlsh** [comment]
Fixed in `1.1.0` - thanks!
